vich_uploader:
    db_driver: orm

    mappings:
       profiles:
           uri_prefix: /Uploads/
           upload_destination: '%kernel.project_dir%/public/Uploads/'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
